In [1]:
import pandas as pd 
import numpy as np

from numpy import genfromtxt
my_data = genfromtxt('dataexercise2.csv', delimiter=',')
# drop first line of nan's (x1,x2..,y)
my_data = np.delete(my_data, (0), axis=0)
np.set_printoptions(suppress=True) #prevent numpy exponential 
                                   #notation on print, default False

In [2]:
Data_X = my_data[:,0:4]
Data_Y = my_data[:,4]
std_dev = 5
# iterations to reach the minimum.
iterations = 1000
# draw random thetas from multivariate normal distribution.
thetas = np.random.multivariate_normal(np.zeros(4,), np.eye(4) * std_dev)
print (thetas)

[-0.12912544  0.70342299  2.81597232 -0.30588716]


In [3]:
# iterate to calculate the Laplace approx.abs
for iteration in range(iterations):
    # calculate the gradiant of the points.
    grad = -Data_X.T @ np.exp(Data_X @ thetas.T) + Data_X.T @ Data_Y
    # calculate the hessian matrix.
    hessian = -Data_X.T @ np.diag(np.exp(Data_X @ thetas.T)) @ Data_X
    # calculate new thetas
    thetas = thetas - (np.linalg.inv(hessian) @ grad)


In [4]:
#Calculate final means and covariance matrices of theta.
means = thetas
print(means)
P = -np.linalg.inv(hessian) 
print(P)

[ 1.12777336  0.42858431  0.01512131 -0.05416601]
[[ 0.03140956 -0.00820031  0.00116572 -0.00139328]
 [-0.00820031  0.00305825 -0.00031134  0.00066138]
 [ 0.00116572 -0.00031134  0.0148073  -0.0014676 ]
 [-0.00139328  0.00066138 -0.0014676   0.01173136]]
